# Generated by Django 4.2.5 on 2023-09-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_part_sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
    ]
