# Generated by Django 4.2.5 on 2023-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_part_sale', '0002_rename_parts_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='part',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='part',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
