# Generated by Django 4.2.5 on 2023-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_part_sale', '0003_remove_part_condition_remove_part_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_qty',
            new_name='part_qty',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='part',
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
